name: Show some logs
run-name: Informative logs

on: 
  pull_request:
    types: [ labeled ]

env:
  documentationLabel: ${{ github.event.label.name == 'documentation' }}
  bugLabel: ${{ github.event.label.name == 'bug' }}

jobs:
  CoolJobName:
    runs-on: ubuntu-latest

    steps:
      - name: first log
        if: ${{ env.documentationLabel }}
        run: echo "Hello world!"
      - name: second log
        if: ${{ env.bugLabel }}
        run: echo "Bye world!"

