name: Show some logs
run-name: Informative logs

on: 
  pull_request:
    types: [ labeled ]

jobs:
  CoolJobName:
    runs-on: ubuntu-latest

    if: github.event.label.name == 'documentation'

    steps:
      - name: first log
        run: echo "Hello world!"
