name: Show some logs
run-name: Informative logs

on: 
  pull_request:
    types: [ labeled ]

env:
  DOCUMENTATION_LABEL: ${{ github.event.label.name == 'documentation' }}
  BUG_LABEL: ${{ github.event.label.name == 'bug' }}

jobs:
  CoolJobName:
    runs-on: ubuntu-latest

    steps:
      - name: first log
        if: ${{ env.DOCUMENTATION_LABEL == 'true' }}
        run: echo "Hello world!"
      - name: second log
        if: ${{ env.BUG_LABEL == 'true' }}
        run: echo "Bye world!"

