name: Show some logs
run-name: Informative logs

on: [ workflow_dispatch ]

env:
  LABEL: ${{ github.event.label.name }}

jobs:
  getMessage:
    runs-on: ubuntu-latest

    outputs:
      message: ${{ steps.message.outputs.generatedMessage }}

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Custom action'
        id: message
        uses: ./.github/actions/getMessage
        with:
          labelName: ${{ env.LABEL }}

  showMessage:
    runs-on: ubuntu-latest

    needs: getMessage

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Show message'
        id: showMessage
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Nice. It works!')
            console.log(${{ needs.getMessage.outputs.message }})
            core.setOutput('finishMessage', 'Pipeline is done')
      - name: 'End message'
        run: echo "${{ steps.showMessage.outputs.finishMessage }}. Bye!"

    

