name: Show some logs
run-name: Informative logs

on: 
  pull_request:
    types: [ labeled ]

env:
  LABEL: ${{ github.event.label.name }}

jobs:
  getMessage:
    runs-on: ubuntu-latest

    outputs:
      message: ${{ steps.message.outputs.generatedMessage }}

    steps:
      - name: 'Custom action'
        id: message
        uses: ./.github/actions/composite/getMessage
        with:
          labelName: ${{ env.LABEL }}

  showMessage:
    runs-on: ubuntu-latest

    needs: getMessage

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Show message'
        id: filtered-label
        uses: actions/github-script@v6
        with:
          script: |
            console.log('Nice. It works!')
            console.log(${{ needs.getMessage.outputs.message }})

    

